version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "fooddb"
    ports:
    - "3306:3306"
    volumes:
    - ./Users/luciano/Programs:/var/lib/mysql